name: Publish
on:
  push:
    tags: v*
  pull_request:
    paths:
    - .github/workflows/publish.yml
    - pyproject.toml
    - setup.py
    - MANIFEST.in

permissions: {}

jobs:
  build:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@a138926f6e4f9667d1306c24f24f5bdcaa01fbab # v2.5.0
    with:
      upload_to_pypi: false
      save_artifacts: true
      test_extras: test
      test_command: pytest --pyargs dust_extinction

  pypi-publish:
    name: Publish
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dust_extinction
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        name: artifacts
        path: dist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
